/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.exerciciotres;

import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author Rafael.Evaristo
 */
public class JanelaConsultarPrato extends javax.swing.JFrame {

    /**
     * Creates new form JanelaConsultarPrato
     */
    
    private Boolean mostrarApagar ;
    private Boolean mostrarClassificar ;
    
    public JanelaConsultarPrato(Boolean mostrarApagar, Boolean mostrarClassificar ) {
        this();
        
        this.mostrarClassificar = mostrarClassificar;
        this.mostrarApagar = mostrarApagar;
        this.btnApagar.setVisible(mostrarApagar);
        this.btnClassificar.setVisible(mostrarClassificar);
        
    }
    
    public JanelaConsultarPrato() {
        initComponents();

        
         for (String nomePrato : Exerciciotres.ListaDePratos.GetPratos().keySet()) {
            Exerciciotres.ListaDePratos.GetPratos().get(nomePrato);
             lstPratos.add( nomePrato);
             
             System.out.println(nomePrato);
             
        }
         

        
//        DefaultListModel<String> listModel = new DefaultListModel<>();
//        
//        jListPratos = new JList<>(listModel);
//        
//        int loop= 0;
//        
//         for (String nomePrato : Exerciciotres.ListaDePratos.GetPratos().keySet()) {
//            Exerciciotres.ListaDePratos.GetPratos().get(nomePrato);
//             listModel.add( loop, nomePrato);
//             
//             System.out.println(nomePrato);
//             
//             loop ++;
//        }
//         
//         jListPratos.setModel(listModel);

        
    }
    
    private void mostraDetalhesPrato(Prato prato){
    
        this.lblNome.setText(prato.getNome());
        this.lblCalorias.setText(prato.getCalorias()+"");
        this.lblClassificacoes.setText(prato.calcularClassificacaoMedia()+"");
        this.lblTipoCozinha.setText(prato.getTipoCozinha());
        this.lblTipoPrato.setText(prato.getTipoPrato());
    
    }
    
    private Prato GetPratoSelecionado(){
    
        int selectedIndex = lstPratos.getSelectedIndex();        
        String selectedPratoKey = lstPratos.getItem(selectedIndex);        
        return Exerciciotres.ListaDePratos.GetPratos().get(selectedPratoKey);   
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lstPratos = new java.awt.List();
        lblNome = new javax.swing.JLabel();
        lblTipoCozinha = new javax.swing.JLabel();
        lblTipoPrato = new javax.swing.JLabel();
        lblCalorias = new javax.swing.JLabel();
        lblClassificacoes = new javax.swing.JLabel();
        btnApagar = new javax.swing.JButton();
        btnClassificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lstPratos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                lstPratosItemStateChanged(evt);
            }
        });
        lstPratos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lstPratosActionPerformed(evt);
            }
        });

        lblNome.setText("Nome");

        lblTipoCozinha.setText("TipoCozinha");

        lblTipoPrato.setText("TipoPrato");

        lblCalorias.setText("Calorias");

        lblClassificacoes.setText("Classificação");

        btnApagar.setText("Apagar");
        btnApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarActionPerformed(evt);
            }
        });

        btnClassificar.setText("Classificar");
        btnClassificar.setToolTipText("");
        btnClassificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClassificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblClassificacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCalorias, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTipoPrato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTipoCozinha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lstPratos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(274, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClassificar)
                    .addComponent(btnApagar))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lstPratos, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(lblNome)
                .addGap(18, 18, 18)
                .addComponent(lblTipoCozinha)
                .addGap(18, 18, 18)
                .addComponent(lblTipoPrato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCalorias)
                .addGap(18, 18, 18)
                .addComponent(lblClassificacoes)
                .addGap(33, 33, 33)
                .addComponent(btnClassificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnApagar)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        new JanelaMenuInicial().setVisible(true);        
    }//GEN-LAST:event_formWindowClosing

    private void lstPratosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lstPratosActionPerformed
         
        mostraDetalhesPrato(this.GetPratoSelecionado());
        
    }//GEN-LAST:event_lstPratosActionPerformed

    private void lstPratosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_lstPratosItemStateChanged
         
        mostraDetalhesPrato(this.GetPratoSelecionado());
    }//GEN-LAST:event_lstPratosItemStateChanged

    private void btnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarActionPerformed
        
        Prato pratoSelecionado = this.GetPratoSelecionado();
        
        if (Exerciciotres.ListaDePratos.removerPrato(pratoSelecionado)){
            this.dispose();
            new JanelaMenuInicial().setVisible(true);  
        }
        
        
        
    }//GEN-LAST:event_btnApagarActionPerformed

    private void btnClassificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClassificarActionPerformed
         //Mostrar um janela para sair
        Object[] op = {"1 estrela","2 estrelas","3 estrelas", "4 estrelas", "5 estrelas"};
        int classificacao;
       classificacao =  JOptionPane.showOptionDialog(null,"Classifique o prato"
               ,"Clasificar",0, JOptionPane.QUESTION_MESSAGE,
                null,op,op[1]);
       if(classificacao >= 0){
           Prato pratoSelecionado = this.GetPratoSelecionado();
           pratoSelecionado.atribuirClassificacao(classificacao+1);
            this.dispose();
            new JanelaMenuInicial().setVisible(true);  
       }
       
       
       
              
    }//GEN-LAST:event_btnClassificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaConsultarPrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaConsultarPrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaConsultarPrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaConsultarPrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaConsultarPrato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApagar;
    private javax.swing.JButton btnClassificar;
    private javax.swing.JLabel lblCalorias;
    private javax.swing.JLabel lblClassificacoes;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTipoCozinha;
    private javax.swing.JLabel lblTipoPrato;
    private java.awt.List lstPratos;
    // End of variables declaration//GEN-END:variables
}
