/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.exerciciodois;

import javax.swing.JOptionPane;

/**
 *
 * @author Rafael.Evaristo
 */
public class TemperatureConverterForm extends javax.swing.JFrame {

    /**
     * Creates new form TemperatureConverterForm
     */
    
    private ConversorTemperatura conversor ;
    
    public TemperatureConverterForm() {
        initComponents();       
        conversor = new ConversorTemperatura(this);
    }
   
    public void exibirResultados(double celsius, double fahrenheit, double kelvin, String unidadeOrigem) {
        String msgToDisplay ;         
        msgToDisplay = "<html>Convertido de " + unidadeOrigem + "<br/>" + "Celsius:" + celsius + "<br/>" + "Fahrenheit:" + fahrenheit  + "<br/>" + "Kelvin:" + kelvin +"</html>" ;        
        this.resultLabel.setText(msgToDisplay);
    }

    
    private boolean isInputValueValid(String originalValue) {
        Double valor;

        if(originalValue.isEmpty()){
            return false;
        }
        
        try {            
            // Check if the convertion is possible
            valor = Double.parseDouble(originalValue);
        } catch (NumberFormatException  e) {
            // Handle the exception of type NumberFormatException 
            return false;
        } 
        
        return true;
    }
    
    private void showError(String message) {        
        JOptionPane.showMessageDialog(null, message,"Erro",0);        
    }
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        celsiusBtn = new javax.swing.JRadioButton();
        kelvinBtn = new javax.swing.JRadioButton();
        fahrenheitBtn = new javax.swing.JRadioButton();
        convertBtn = new javax.swing.JButton();
        origianlValueBox = new javax.swing.JTextField();
        resultLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(celsiusBtn);
        celsiusBtn.setText("celsius");

        buttonGroup1.add(kelvinBtn);
        kelvinBtn.setText("fahrenheit");
        kelvinBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelvinBtnActionPerformed(evt);
            }
        });

        buttonGroup1.add(fahrenheitBtn);
        fahrenheitBtn.setText("kelvin");

        convertBtn.setText("Convert");
        convertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertBtnActionPerformed(evt);
            }
        });

        origianlValueBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                origianlValueBoxActionPerformed(evt);
            }
        });

        resultLabel.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        resultLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        resultLabel.setText("À espera de conversão");
        resultLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        resultLabel.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        resultLabel.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(origianlValueBox, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(convertBtn)
                    .addComponent(fahrenheitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(celsiusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kelvinBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addComponent(resultLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(celsiusBtn)
                            .addComponent(origianlValueBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fahrenheitBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kelvinBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(convertBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        resultLabel.getAccessibleContext().setAccessibleName("ResultLabel");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kelvinBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelvinBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kelvinBtnActionPerformed

    private void origianlValueBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_origianlValueBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_origianlValueBoxActionPerformed

    
    
    private void convertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertBtnActionPerformed

        String valueToConvertText = origianlValueBox.getText(); 
        
        if(! this.isInputValueValid(valueToConvertText)){
            this.showError(valueToConvertText + ": Não é valido");
            return;
        }
        
        double originalValue = Double.parseDouble(valueToConvertText);
        
        if(this.kelvinBtn.isSelected()){
            this.conversor.converterKelvin(originalValue);
        }
        else if (this.celsiusBtn.isSelected()){
            this.conversor.converterCelsius(originalValue);
        }
        else if(this.fahrenheitBtn.isSelected()) {
            this.conversor.converterFahrenheit(originalValue);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_convertBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TemperatureConverterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TemperatureConverterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TemperatureConverterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TemperatureConverterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TemperatureConverterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton celsiusBtn;
    private javax.swing.JButton convertBtn;
    private javax.swing.JRadioButton fahrenheitBtn;
    private javax.swing.JRadioButton kelvinBtn;
    private javax.swing.JTextField origianlValueBox;
    private javax.swing.JLabel resultLabel;
    // End of variables declaration//GEN-END:variables
}
